- name: download node exporter tar file
  get_url:
    url: "https://your_url/node_exporter-1.3.0.linux-amd64.tar.gz"
    dest: /opt

- name: Unzip the package
  unarchive: 
    src: /opt/node_exporter-1.3.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

- name: remove tar package
  file:
    path: /opt/node_exporter-1.3.0.linux-amd64.tar.gz
    state: absent

- name: Create group
  group:
    name: operator
    state: present

- name: add user
  user: 
    name: operator
    comment: "user to run node_Exporter"
    group: operator

- name: Change ownership of /opt/node_exporter-1.3.0.linux-amd64
  file:
    path: /opt/node_exporter-1.3.0.linux-amd64
    owner: operator
    group: operator
    recurse: yes

- name: create node_exporter service
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable node_exporter service
  systemd:
    name: node_exporter
    enabled: yes

- name: Start node_exporter service
  systemd:
    name: node_exporter
    state: started